import type { Metadata } from "next";
import "./globals.css";
import { ToastContainer } from "react-toastify";
import "react-toastify/dist/ReactToastify.css";
import Nav from "@/components/Nav";
import { Suspense } from "react";

export const metadata: Metadata = {
  title: "منصة العبقري التعليمية",
  description: "Generated by create next app",
  icons: {
    icon: "/main-logo.png",
  },
};

const TeacherLayout = ({
  children,
}: Readonly<{ children: React.ReactNode }>) => {
  return (
    <html>
      <body>
        <Nav />
        <div className="flex ctm-height">
          <div className="flex-1 p-4">
            <div className=" p-3 h-full bg-slate-50 rounded-md">
                 <Suspense fallback={<div>جاري التحميل ........</div>}>
            {children}
          </Suspense>
            </div>
          </div>
        </div>

        <ToastContainer position="top-right" autoClose={3000} />
      </body>
    </html>
  );
};

export default TeacherLayout;


