import type { Metadata } from "next";
import "./globals.css";
import "react-toastify/dist/ReactToastify.css";

export const metadata: Metadata = {
  title: "منصة بصيرة التعليمية",
  description: "Generated by create next app",
  icons: {
    icon: '/basira.svg'
  }
};

import Menu from "@/components/Menu";
import { adminMenuLinks } from "@/data/data";
import Nav from "@/components/Nav";

const layout = ({ children }: Readonly<{ children: React.ReactNode }>) => {
  return (
    <html>
      <body>
        <Nav />
        <div className="flex ctm-height">
          <div className="p-4 w-[250px] relative hidden lg:block">
            <Menu data={adminMenuLinks} />{" "}
          </div>
          <div className="flex-1 p-4">
            <div className=" p-3 h-full bg-slate-50 rounded-md">{children}</div>
          </div>
        </div>
      </body>
    </html>
  );
};

export default layout;


