import { Suspense } from "react"; // ✅ import Suspense from React
import type { Metadata } from "next";
import "./globals.css";
import Nav from "../components/Nav";
import Footer from "../components/Footer";
import { ToastContainer } from "react-toastify";
import "react-toastify/dist/ReactToastify.css";
import ClientProvider from "@/components/ClientProvider";

export const metadata: Metadata = {
  title: "منصة بصيرة التعليمية",
  description: "Generated by create next app",
  icons: {
    icon: '/basira.svg'
  }
};

export default function RootLayout({
  children,
}: Readonly<{ children: React.ReactNode }>) {
  return (
    <html lang="en">
      <body>
        <main>
          <ClientProvider />
          <Nav />
          
          <Suspense fallback={<div>جاري التحميل ........</div>}>
            {children}
          </Suspense>
          
          <Footer />
          <ToastContainer position="top-right" autoClose={3000} />
        </main>
      </body>
    </html>
  );
}
