
import type { Metadata } from "next";
import "./globals.css";
import Nav from "../components/Nav";
import Footer from "../components/Footer";
import ProgressProvider from "@/components/progress-provider";
import { ToastContainer } from "react-toastify";
import "react-toastify/dist/ReactToastify.css";
import ClientProvider from "@/components/ClientProvider";

export const metadata: Metadata = {
  title: "منصة بصيرة التعليمية",
  description: "Generated by create next app",
};

export default function RootLayout({ children, }: Readonly<{ children: React.ReactNode;}>) {
    
  return (
    <html lang="en">
      <body>
           <main>
                <ClientProvider />
                <Nav />
                    {/* <ProgressProvider> {children} </ProgressProvider> */}
                    {children}
                <Footer />
                <ToastContainer position="top-right" autoClose={3000} />
           </main>
      </body>
    </html>
  );
}
